[WIP] add asgi support to docker
VNG-Realisatie/gemma-zaken-demo pull request #11
Opened 2019-06-03 13:25 UTC by annashamray

2019-06-03 15:30 UTC, annashamray commented
**Changes:**
1. Replace wsg` server (uwsgi) with the asgi one `(daphne`)
1. Add `nginx` to docker configuration to manage static files

2019-06-06 11:31 UTC, sergei-maertens requested changes

2019-06-06 11:31 UTC, sergei-maertens commented on Dockerfile
> +RUN /app/env/bin/pip install daphne
add this to `requirements.in` please, always use pinned versions

2019-06-06 11:31 UTC, sergei-maertens commented on bin/docker_start.sh
> +#uwsgi \
remove code instead of commenting please

2019-06-06 11:33 UTC, sergei-maertens requested changes
https://github.com/VNG-Realisatie/gemma-zaken-demo/blob/master/src/zac/conf/settings.py#L195 - this is not going to work, the redis host will have to be passed as envvar as well so that it can talk to a redis DB in a different container.

2019-06-11 10:32 UTC, annashamray reviewed
I explicitly added `REDIS_HOST` to `docker-compose.yml`, but it could work without it because variable REDIS_HOST is assigned in `conf/docker.py`

2019-06-11 10:32 UTC, annashamray commented on Dockerfile
> +RUN /app/env/bin/pip install daphne
`requirements.in` is updated

2019-06-11 10:32 UTC, annashamray commented on bin/docker_start.sh
> +#uwsgi \
commented code is removed

2019-06-12 09:26 UTC, sergei-maertens commented on Dockerfile
> +RUN /app/env/bin/pip install daphne
I've removed this line because now it's installed through `requirements.txt`

2019-06-12 09:27 UTC, sergei-maertens commented
I missed that the `REDIS_HOST` was defined in `docker.py` settings file. The settings are a mess, I'll condense them down to minimal set of overrides.

2019-06-12 09:27 UTC, sergei-maertens approved these changes

2019-06-12 09:51 UTC, merged